services:
  keycloak:
    image: spring_security_devox_2022-keycloak-1-configured:latest
    command:
      - start-dev
    ports:
      - '8081:8080'
    environment:
      - KC_BOOTSTRAP_ADMIN_USERNAME=admin
      - KC_BOOTSTRAP_ADMIN_PASSWORD=admin